image: centos:7

before_script:
  # Install required system packages.
  - yum -y install git make zip

  # Copy the project into the GOPATH.
  - mkdir -p /go/src/gitlab.com/crankykernel/cryptoxscanner
  - cp -a . /go/src/gitlab.com/crankykernel/cryptoxscanner

  # Download and install Go.
  - curl -o /tmp/go.tar.gz -L https://dl.google.com/go/go1.10.3.linux-amd64.tar.gz
  - (cd /usr/local && tar xf /tmp/go.tar.gz)

  # Use nvm to install the latest LTS node.
  - curl --silent -o - https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - . ${NVM_DIR}/nvm.sh
  - nvm install --lts
  - nvm use --lts

build:
  script: |
    yum -y install epel-release
    yum -y install mingw64-gcc mingw32-gcc
    export GOPATH=/go
    export PATH=$GOPATH/bin:/usr/local/go/bin:$PATH
    go version
    go env
    cd /go/src/gitlab.com/crankykernel/cryptoxscanner
    make install-deps
    CC=gcc GOOS=linux GOARCH=amd64 make dist
    CC=x86_64-w64-mingw32-gcc GOOS=windows GOARCH=amd64 make dist
    CC=i686-w64-mingw32-gcc GOOS=windows GOARCH=386 make dist

    cp dist/*.zip ${CI_PROJECT_DIR}

  artifacts:
    paths:
      - "*.zip"

